pypicloud:
  restart: always
  image: stevearc/pypicloud
  volumes:
    - /etc/pypicloud:/etc/pypicloud
  environment:
    - TZ=America/Toronto
    - S3_USE_SIGV4=True

nginx:
  restart: always
  build: ./nginx/
  ports:
    - 80:80
    - 443:443
  environment:
    - TZ=America/Toronto
  links:
    - pypicloud

